### ISSUE TITLE
Errors when installing the rii package via pip for the first time

### ISSUE THREAD

**Issue by matsui528** [matsui528/rii#25]
When installing the rii package for the first time via `pip install rii`, the package can be installed as usual but we get the following error messages.
```
Collecting rii
  Downloading https://files.pythonhosted.org/packages/37/79/379308df392bc07d1c51b288884c2e85ef193c67f7a6908181392778a4e0/rii-0.2.3.tar.gz
Collecting pybind11>=2.2 (from rii)
  Downloading https://files.pythonhosted.org/packages/f2/7c/e71995e59e108799800cb0fce6c4b4927914d7eada0723dd20bae3b51786/pybind11-2.2.4-py2.py3-none-any.whl (145kB)
Collecting nanopq (from rii)
  Downloading https://files.pythonhosted.org/packages/25/2b/afadc20d14bffe91560543826fee41c4d87ab540b2191a9d5dfdeb783304/nanopq-0.1.6-py3-none-any.whl
Requirement already satisfied: numpy in ./anaconda/lib/python3.6/site-packages (from nanopq->rii) (1.15.2)
Requirement already satisfied: scipy in ./anaconda/lib/python3.6/site-packages (from nanopq->rii) (1.1.0)
Building wheels for collected packages: rii
  Running setup.py bdist_wheel for rii: started
  Running setup.py bdist_wheel for rii: finished with status 'error'
  Complete output from command /home/ubuntu/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-q9a9hf6g/rii/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-tnix8m2r --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/tests
  copying tests/test_rii.py -> build/lib.linux-x86_64-3.6/tests
  copying tests/context.py -> build/lib.linux-x86_64-3.6/tests
  copying tests/__init__.py -> build/lib.linux-x86_64-3.6/tests
  creating build/lib.linux-x86_64-3.6/rii
  copying rii/rii.py -> build/lib.linux-x86_64-3.6/rii
  copying rii/__init__.py -> build/lib.linux-x86_64-3.6/rii
  running build_ext
  creating tmp
  gcc -pthread -B /home/ubuntu/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ubuntu/anaconda/include/python3.6m -c /tmp/tmpgabfpgat.cpp -o tmp/tmpgabfpgat.o -std=c++14
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  gcc -pthread -B /home/ubuntu/anaconda/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ubuntu/anaconda/include/python3.6m -c /tmp/tmp1ecn6a1p.cpp -o tmp/tmp1ecn6a1p.o -fvisibility=hidden
  cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
  building 'main' extension
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-q9a9hf6g/rii/setup.py", line 128, in <module>
      zip_safe=False
    File "/home/ubuntu/anaconda/lib/python3.6/site-packages/setuptools/__init__.py", line 140, in setup
      return distutils.core.setup(**attrs)
    File "/home/ubuntu/anaconda/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/ubuntu/anaconda/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/home/ubuntu/anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/ubuntu/anaconda/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 188, in run
      self.run_command('build')
    File "/home/ubuntu/anaconda/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/ubuntu/anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/ubuntu/anaconda/lib/python3.6/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/ubuntu/anaconda/lib/python3.6/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/ubuntu/anaconda/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/home/ubuntu/anaconda/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 78, in run
      _build_ext.run(self)
    File "/home/ubuntu/anaconda/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
      _build_ext.build_ext.run(self)
    File "/home/ubuntu/anaconda/lib/python3.6/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/tmp/pip-install-q9a9hf6g/rii/setup.py", line 112, in build_extensions
      build_ext.build_extensions(self)
    File "/home/ubuntu/anaconda/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
      self.build_extension(ext)
    File "/home/ubuntu/anaconda/lib/python3.6/site-packages/setuptools/command/build_ext.py", line 199, in build_extension
      _build_ext.build_extension(self, ext)
    File "/home/ubuntu/anaconda/lib/python3.6/distutils/command/build_ext.py", line 533, in build_extension
      depends=ext.depends)
    File "/home/ubuntu/anaconda/lib/python3.6/distutils/ccompiler.py", line 566, in compile
      depends, extra_postargs)
    File "/home/ubuntu/anaconda/lib/python3.6/distutils/ccompiler.py", line 341, in _setup_compile
      pp_opts = gen_preprocess_options(macros, incdirs)
    File "/home/ubuntu/anaconda/lib/python3.6/distutils/ccompiler.py", line 1075, in gen_preprocess_options
      pp_opts.append("-I%s" % dir)
    File "/tmp/pip-install-q9a9hf6g/rii/setup.py", line 30, in __str__
      import pybind11
  ModuleNotFoundError: No module named 'pybind11'
  
  ----------------------------------------
  Failed building wheel for rii
  Running setup.py clean for rii
Failed to build rii
Installing collected packages: pybind11, nanopq, rii
  Running setup.py install for rii: started
    Running setup.py install for rii: finished with status 'done'
Successfully installed nanopq-0.1.6 pybind11-2.2.4 rii-0.2.3
```
This doesn't happen again when reinstalling the rii: `pip uninstall rii nanopq pybind11 && pip install rii`

We can reproduce this again by deleting pip cache: `pip uninstall rii nanopq pybind11 && rm -rf ~/.cache/pip/ && pip install rii`

Any comments or PRs are highly welcome!

**Comment by matsui528** [comment]
Tested in the following environment:
- AWS EC2 c5.18xlarge
- Ubuntu 16.04
- Anaconda
- Python 3.6

**Comment by domarps** [comment]
Can confirm this behavior in MacOS environment, Python3.5 and Anaconda. Fortunately, prefixing the CXX flag worked for me.

```
CXX=clang pip install rii
```

**Comment by matsui528** [comment]
Oh I see. I haven't compiled this project using clang, so not sure it works correctly. But anyway thanks for your report!

It seem pqkmeans lib depends on pybind11, and something happens on pybind11 when installing pqkmeans lib... (But there's no error when installing pqkmeans alone on the fresh environment. why?)

**Comment by matsui528** [comment]
Deleting a submodule of pqkmeans doesn't fix  https://github.com/matsui528/rii/pull/32

Updating setup.py does fix https://github.com/matsui528/rii/pull/33

Now rii can be installed without error
